# Generated by Django 6.0.4 on 2026-04-30 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrateur', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupe',
            name='filier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='Administrateur.filier'),
        ),
        migrations.AddField(
            model_name='module',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_specific', to='Administrateur.filier'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='Administrateur.module'),
        ),
        migrations.AddField(
            model_name='filier',
            name='modules',
            field=models.ManyToManyField(related_name='filieres', to='Administrateur.module'),
        ),
        migrations.AddField(
            model_name='session',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrateur.matiere'),
        ),
    ]
