# Generated by Django 6.0.4 on 2026-04-30 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrateur', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filier',
            name='modules',
        ),
    ]
