# Generated by Django 6.0.4 on 2026-05-04 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrateur', '0003_remove_filier_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Administrateur.groupe'),
        ),
    ]
