# Generated by Django 6.0.4 on 2026-04-30 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrateur', '0001_initial'),
        ('Etudiant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CIN', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Professuer',
                'verbose_name_plural': 'Professeurs',
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Status_presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('note', models.DecimalField(decimal_places=2, max_digits=2)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Etudiant.etudiant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrateur.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='presence',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrateur.session')),
            ],
        ),
    ]
