# Generated by Django 6.0.4 on 2026-04-29 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Professeur', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professeur',
            name='username',
        ),
    ]
