# Generated by Django 6.0.4 on 2026-04-30 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Etudiant', '0002_initial'),
        ('Professeur', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rapport',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Etudiant.etudiant'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Professeur.professeur'),
        ),
        migrations.AddField(
            model_name='status_presence',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Etudiant.etudiant'),
        ),
        migrations.AddField(
            model_name='presence',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Professeur.status_presence'),
        ),
    ]
