# Generated by Django 6.0.4 on 2026-05-04 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrateur', '0004_session_groupe'),
        ('Etudiant', '0002_initial'),
        ('Professeur', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status_presence',
            name='etudiant',
        ),
        migrations.CreateModel(
            name='absence',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Etudiant.etudiant')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrateur.session')),
            ],
        ),
        migrations.DeleteModel(
            name='presence',
        ),
        migrations.DeleteModel(
            name='Status_presence',
        ),
    ]
