# Generated by Django 6.0.4 on 2026-05-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrateur', '0005_alter_session_id'),
        ('Professeur', '0004_professeur_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professeur',
            name='group',
        ),
        migrations.AddField(
            model_name='professeur',
            name='groupe',
            field=models.ManyToManyField(related_name='professeurs', to='Administrateur.groupe'),
        ),
    ]
