# Generated by Django 6.0.4 on 2026-05-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professeur', '0005_remove_professeur_group_professeur_groupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
