# Generated by Django 6.0.4 on 2026-04-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_alter_custumuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custumuser',
            name='email',
            field=models.EmailField(blank=True, max_length=50, unique=True),
        ),
    ]
